"""Enhance User table to reflect sign-up form changes (add name, username, age, and gender columns)

Revision ID: 32ec1553318e
Revises: 4c4ecf7eb367
Create Date: 2025-05-03 03:20:30.354645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ec1553318e'
down_revision = '4c4ecf7eb367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=22), nullable=False))
        batch_op.create_unique_constraint('unique_user_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')
        batch_op.drop_column('username')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
