"""Wake datetime not nullable

Revision ID: 45dfd2a5461d
Revises: c76f0aaddfb1
Create Date: 2025-05-14 14:28:18.872215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45dfd2a5461d'
down_revision = 'c76f0aaddfb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.alter_column('wake_datetime',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.alter_column('wake_datetime',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
