"""Add shared_entries table

Revision ID: 889f98b8f08a
Revises: 32ec1553318e
Create Date: 2025-05-09 19:38:06.177611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889f98b8f08a'
down_revision = '32ec1553318e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shared_entries',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['entry.entry_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shared_entries')
    # ### end Alembic commands ###
